#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

if [ $1 = "--nomesh" ]
then
    scripts/Allclean.nomesh
else
    cleanCase
    rm -rf 0
    rm -rf constant/extendedFeatureEdgeMesh/
    rm -f constant/triSurface/*.eMesh*
    rm -rf oldLogs
    rm -f constant/triSurface/blades.stl
fi

