#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ $1 != "--postmesh" ]
then
    scripts/Allrun.pre
fi

scripts/Allrun.postmesh
